# Generated by Django 5.0.4 on 2024-05-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
