# Generated by Django 5.0.4 on 2024-09-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_streamplatform_watchlist_delete_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamplatform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='streamplatform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
