# Generated by Django 5.0.4 on 2024-09-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_streamplatform_created_at_streamplatform_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='content_type',
            field=models.CharField(blank=True, choices=[('Movie', 'movie'), ('TV Series', 'series')], null=True),
        ),
    ]
